### ISSUE TITLE
Support templating

### ISSUE THREAD

**Issue by sznorbert07** [OfficeDev/acpreviewer#7]
Hi, thank you so much for this extension 🎉, it really can help the development of Teams Bots.

It would be great to support Adaptive Cards templating. The cards which we use contains multiple templates for texts and for image URLs also.
We are using the AdaptiveCards.Templating nuget package to populate our templates. (https://www.nuget.org/packages/AdaptiveCards.Templating)

Here is a part of the template and a screenshot of how it looks like.
```
...
{
  "type": "TextBlock",
  "text": "${$root.title}",
  "wrap": true,
  "fontType": "Default",
  "size": "Large",
  "weight": "Bolder",
  "spacing": "None",
  "separator": true
},
...
```
![image](https://github.com/OfficeDev/acpreviewer/assets/60083754/5587f84e-6704-45bc-bb67-35a4b69ce85d)

I would expect to have a text field for every field detected in the template.

**Comment by dooriya** [comment]
Hi @sznorbert07,

Thank you for feedback! Actually the ACP extension has already supported [Adaptive Card Templating Language](https://learn.microsoft.com/en-us/adaptive-cards/templating/language).

To preview your card template with data object, you can use command `Adaptive Card: New Data File` to create a data file for your template JSON file. For example: https://github.com/OfficeDev/acpreviewer/blob/main/card-samples/card-elements/template.data.json is the corresponding data file of `template.json`, then ACP will automatically resolve the $variables when you preview the card.

**Comment by sznorbert07** [comment]
Hi @dooriya,

Thank you for your quick answer. I have probably missed the information.
